# Generated by Django 2.2.5 on 2023-01-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePickerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=300)),
                ('genre', models.TextField(blank=True, default='', max_length=300)),
                ('decade', models.IntegerField(blank=True, default='')),
                ('time', models.DateTimeField(blank=True, default='')),
            ],
        ),
    ]
