# Generated by Django 2.2.5 on 2023-01-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePicker', '0002_auto_20230124_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepickermodel',
            name='decade',
        ),
        migrations.RemoveField(
            model_name='moviepickermodel',
            name='time',
        ),
        migrations.AddField(
            model_name='moviepickermodel',
            name='date',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='moviepickermodel',
            name='review',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='moviepickermodel',
            name='genre',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='moviepickermodel',
            name='name',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
    ]
