# Generated by Django 2.2.5 on 2023-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePicker', '0005_auto_20230125_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepickermodel',
            name='Date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='moviepickermodel',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='moviepickermodel',
            name='Review',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='moviepickermodel',
            name='Title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
