# Generated by Django 2.2.5 on 2023-01-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePicker', '0006_auto_20230127_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepickermodel',
            old_name='Date',
            new_name='Rate',
        ),
        migrations.AlterField(
            model_name='moviepickermodel',
            name='Review',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
